name: NyanCat
description: "NyanCat"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  flutter_background_service: ^5.0.10
  http: ^1.2.1
  device_info_plus: ^12.3.0
  just_audio: ^0.10.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/nyan_bg.jpg
    - assets/images/nyan_cat.png
